# Generated by cucumber-sinatra. (2013-09-24 12:00:40 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'

Capybara.app = Sinatra::Application

class BookmarkWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookmarkWorld.new
end

DatabaseCleaner.strategy = :truncation

Before do |scenario|
 	DatabaseCleaner.start
end

After do |scenario|
 	DatabaseCleaner.clean 
end
